// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIs-Ii5Z89f7KkeFqlLObkSd4XIcEQo6w',
    appId: '1:75300035187:web:b7fd2f9dcfd6138d3ae806',
    messagingSenderId: '75300035187',
    projectId: 'flutter-health-app-9f31d',
    authDomain: 'flutter-health-app-9f31d.firebaseapp.com',
    databaseURL: 'https://flutter-health-app-9f31d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-health-app-9f31d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzlDvwE9r01G3SQHB1SncgfFPcWfR0gUo',
    appId: '1:75300035187:android:53805e04bd949f873ae806',
    messagingSenderId: '75300035187',
    projectId: 'flutter-health-app-9f31d',
    databaseURL: 'https://flutter-health-app-9f31d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-health-app-9f31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqRYE7AHRrWD6Pg9RgaeIgczgluWkdE58',
    appId: '1:75300035187:ios:c2f657344a8c7ebf3ae806',
    messagingSenderId: '75300035187',
    projectId: 'flutter-health-app-9f31d',
    databaseURL: 'https://flutter-health-app-9f31d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-health-app-9f31d.appspot.com',
    iosBundleId: 'com.example.healthApp',
  );
}
